name: "VirusTotal Artifacts Scan"
description: "Scan files and releases with VirusTotal API"
author: "WoozyMasta"
branding:
  icon: "shield"
  color: "red"

inputs:
  github_token:
    description: "GitHub Token from secrets.GITHUB_TOKEN"
    required: true
  vt_api_key:
    description: "VirusTotal API Token from secrets"
    required: true
  file_globs:
    description: "File Globs to Process"
    required: false
  excluded_extensions:
    description: "Extensions to exclude .json,.txt,.log"
    required: false
  rate_limit:
    description: "Per Minute Rate Limit for API Calls"
    required: false
    default: "4"
  update_release:
    description: "Update Release Notes with VT Links"
    required: false
    default: "true"

outputs:
  results:
    description: "Generated Docker tags"

runs:
  using: "node20"
  main: "dist/index.js"
